# Generated by Django 5.0.1 on 2024-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user_picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='user_picture/'),
        ),
    ]
