# Generated by Django 5.0.1 on 2024-02-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanelapp', '0002_person_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('airline_ticket_code', models.CharField(max_length=100)),
                ('airline_class', models.CharField(max_length=100)),
                ('airline_from', models.CharField(max_length=100)),
                ('airline_to', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=100)),
                ('airline_date', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('nid_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bus_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_ticket_code', models.CharField(max_length=100)),
                ('bus_class', models.CharField(max_length=100)),
                ('bus_from', models.CharField(max_length=100)),
                ('bus_to', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=100)),
                ('bus_date', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Train_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('train_ticket_code', models.CharField(max_length=100)),
                ('train_class', models.CharField(max_length=100)),
                ('train_from', models.CharField(max_length=100)),
                ('train_to', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=100)),
                ('train_date', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('nid_number', models.CharField(max_length=50)),
            ],
        ),
    ]
