# Generated by Django 5.0.1 on 2024-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanelapp', '0004_airline_ticket_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_ticket',
            name='coach',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
